### ISSUE TITLE
Console errors on Mario example, game won't start

### ISSUE THREAD

**Issue by onearmfrog** [IceCreamYou/HTML5-Canvas-Game-Boilerplate#1]
I have these errors in the console:
Uncaught TypeError: Cannot read property 'startCoords' of undefined combined.min.js:8
Uncaught TypeError: Cannot call method 'draw' of undefined 

Running on a wamp environment, chrome.

**Comment by IceCreamYou** [comment]
Whoops, must have broken it recently. I'll try to dig into it tonight.

**Comment by IceCreamYou** [comment]
Fixed in https://github.com/IceCreamYou/HTML5-Canvas-Game-Boilerplate/commit/28d01bbda9b4a559096258e835a913f6bb7dcdc1

**Comment by onearmfrog** [comment]
Works great now. Thanks!
