### ISSUE TITLE
By-reference arguments when creating new TileMap objects

### ISSUE THREAD

**Issue by nossidge** [IceCreamYou/HTML5-Canvas-Game-Boilerplate#5]
When creating multiple new `TileMap` objects, there is a problem with re-using the same array as an input argument:

```javascript
var gridAsString = 'B\nP';
var gridAsArray = [['B'], ['P']];

// Using a string works correctly:
var blocks = new TileMap(gridAsString, { B: Block });
var pots   = new TileMap(gridAsString, { P: Pot });

// But using an array is broken:
var blocks = new TileMap(gridAsArray, { B: Block });
var pots   = new TileMap(gridAsArray, { P: Pot });
```

I believe this is because of the code overwriting the `grid` argument by reference. By the time the `pots` collection is being created, `gridAsArray` is already partly filled with `Block` objects.

To fix this, I just added one line immediately below the function start:

```javascript
...
function TileMap(grid, map, options) {
  var grid = JSON.parse(JSON.stringify(grid));

  // Setup and options
...
```

I think this is all the cloning that is necessary. I'm not a Javascript native, so there may be something I've overlooked.

Thanks.

**Comment by IceCreamYou** [comment]
Good catch.

I would suggest that rather than modifying the library, as a workaround you could do this:

```js
var gridAsArray = [['B'], ['P']];
function clone(v) { JSON.parse(JSON.stringify(v)); }
var blocks = new TileMap(clone(gridAsArray), { B: Block });
var pots   = new TileMap(clone(gridAsArray), { P: Pot });
```

However, it's probably more convenient to specify the grid as a string. You could even do something like this:

```js
var gridAsArray = [['B'], ['P']];
var gridAsString = gridAsArray.map((row) => row.join('')).join('\n'); // convert to string
var blocks = new TileMap(gridAsString, { B: Block });
var pots   = new TileMap(gridAsString, { P: Pot });
```

**Comment by nossidge** [comment]
My problem with the string specification is that I am reading in from a [Tiled](https://www.mapeditor.org/) map, where the tiles are numbered and could be more than one character long:

    1,2,2,2,2,2,2,2,2,2,2,2,2,2,3,
    7,20,20,20,20,20,20,20,20,20,20,20,20,20,9,
    7,20,20,20,20,20,20,20,20,20,20,20,20,20,9,
    7,20,20,20,20,0,0,0,0,20,20,20,20,20,9,
    7,20,20,20,20,23,20,20,21,0,20,20,20,20,9,
    7,20,20,20,0,23,23,21,0,0,20,20,20,20,9,
    7,20,20,20,0,0,20,21,0,0,20,20,20,20,9,
    7,20,20,20,0,0,0,0,20,20,20,20,20,20,9,
    7,20,20,20,20,20,20,20,20,20,20,20,20,20,9,
    7,20,20,20,20,20,20,20,20,20,20,20,20,20,9,
    13,14,14,14,14,14,14,14,14,14,14,14,14,14,15

So my actual code looks more like this:

```javascript
var walls = new TileMap(
  grid(),
  {
    2:  WallN,
    9:  WallE,
    14: WallS,
    7:  WallW,
    1:  WallInnerNW,
    3:  WallInnerNE,
    15: WallInnerSE,
    13: WallInnerSW
  },
  { cellSize: [tileSize, tileSize] }
);
```

I'm modifying the library in a few other places too, so I think I'll leave my solution in place in my own implementation, at least while I'm prototyping my game.

**Comment by IceCreamYou** [comment]
Thanks. I have pushed a fix and it will be in the next release.
